@extends('layouts.admin')
@section('title', 'Customers')
@section('page-title', 'Customers')
@section('content')
<div class="mb-8 flex flex-col justify-between gap-4 md:flex-row md:items-end"><div><p class="text-sm text-slate-500">People management</p><h2 class="mt-1 text-3xl font-black text-slate-900">Customers</h2></div><a href="{{ route('admin.customers.create') }}" class="rounded-xl bg-blue-600 px-5 py-3 text-sm font-bold text-white hover:bg-blue-700">+ Add Customer</a></div>
<form method="GET" class="mb-6 flex flex-col gap-3 rounded-2xl bg-white p-4 shadow-sm ring-1 ring-slate-200 sm:flex-row"><input name="search" value="{{ request('search') }}" placeholder="Name, email, or phone" class="flex-1 rounded-xl border border-slate-300 px-4 py-3"><select name="status" class="rounded-xl border border-slate-300 bg-white px-4 py-3"><option value="">All statuses</option><option value="active" @selected(request('status') === 'active')>Active</option><option value="inactive" @selected(request('status') === 'inactive')>Inactive</option></select><button class="rounded-xl bg-slate-900 px-5 py-3 text-sm font-bold text-white">Search</button><a href="{{ route('admin.customers.index') }}" class="rounded-xl border border-slate-200 px-5 py-3 text-center text-sm font-semibold text-slate-600">Reset</a></form>
<div class="overflow-hidden rounded-2xl bg-white shadow-sm ring-1 ring-slate-200"><div class="overflow-x-auto"><table class="w-full min-w-[800px] text-left text-sm"><thead class="bg-slate-50 text-xs uppercase tracking-wider text-slate-500"><tr><th class="px-6 py-4">Customer</th><th class="px-6 py-4">Phone</th><th class="px-6 py-4">Orders</th><th class="px-6 py-4">Status</th><th class="px-6 py-4 text-right">Actions</th></tr></thead><tbody class="divide-y">
@forelse($customers as $customer)<tr class="hover:bg-slate-50"><td class="px-6 py-4"><div class="font-bold">{{ $customer->name }}</div><div class="mt-1 text-xs text-slate-500">{{ $customer->email ?: 'No email' }}</div></td><td class="px-6 py-4">{{ $customer->phone ?: '—' }}</td><td class="px-6 py-4">{{ $customer->orders_count ?? $customer->orders()->count() }}</td><td class="px-6 py-4"><span class="rounded-full px-3 py-1 text-xs font-semibold {{ $customer->is_active ? 'bg-emerald-50 text-emerald-700' : 'bg-slate-100 text-slate-600' }}">{{ $customer->is_active ? 'Active' : 'Inactive' }}</span></td><td class="px-6 py-4 text-right"><form method="POST" action="{{ route('admin.customers.status', $customer) }}" class="mr-4 inline" data-swal-confirm data-swal-title="Change customer status?" data-swal-text="{{ $customer->is_active ? 'This customer will no longer be available for billing.' : 'This customer will be available for billing again.' }}" data-swal-icon="question" data-swal-confirm-text="Yes, change status">@csrf @method('PATCH')<button class="font-semibold {{ $customer->is_active ? 'text-amber-600' : 'text-emerald-600' }}">{{ $customer->is_active ? 'Deactivate' : 'Activate' }}</button></form><a href="{{ route('admin.customers.edit', $customer) }}" class="mr-4 font-semibold text-blue-600">Edit</a><form method="POST" action="{{ route('admin.customers.destroy', $customer) }}" class="inline" data-swal-confirm data-swal-title="Delete customer?" data-swal-text="This action cannot be undone." data-swal-confirm-text="Yes, delete">@csrf @method('DELETE')<button class="font-semibold text-red-600">Delete</button></form></td></tr>@empty<tr><td colspan="5" class="px-6 py-12 text-center text-slate-400">No customers have been added yet.</td></tr>@endforelse
</tbody></table></div>@if($customers->hasPages())<div class="border-t px-6 py-4">{{ $customers->links() }}</div>@endif</div>
@endsection